[project]
name = "electricitypriceprediction"
version = "0.1.0"
authors = ["ThanosPourikis <thanos.pourikis@gmail.com>"]
readme = "README.md"
requires-python = ">=3.12"


[tool.ruff]
target-version = "py312"
line-length = 200

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]

ignore = [
    "E501",     # line too long
    "B008",     # do not perform function calls in argument defaults
#    "C901",    # too complex
    "B904",     # `except` clause, raise exceptions with `raise ... from err`
    "E722",     # Do not use bare `except`
    "B007",     # Loop control variable not used within loop body
    "W191",     # indentation contains tabs
]

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[dependency-groups]
dev = [
    "beautifulsoup4>=4.13.4",
    "pandas>=2.2.3",
    "pre-commit>=4.3.0",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "sqlmodel>=0.0.24",
]
