linear_params:
  requirements:
    n_jobs: -1

  requirements_units:
    n_jobs: -1

  requirements_weather:
    n_jobs: -1
    
  requirements_units_weather:
    n_jobs: -1


knn_params:
  requirements:
    metric: manhattan
    n_neighbors: 6
    weights: distance

  requirements_units:
      metric: manhattan
      n_neighbors: 4
      weights: distance

  requirements_weather:
    metric: manhattan
    n_neighbors: 7
    weights: distance

  requirements_units_weather:
    metric: manhattan
    n_neighbors: 4
    weights: distance
  
xgb_params:
  requirements:
    learning_rate: 0.09
    colsample_bylevel: 0.8
    subsample: 0.8
    n_estimators: 150
    max_depth: 9
    learning_rate: 0.09
    colsample_bylevel: 0.8
    subsample: 0.8
    n_estimators: 150
    max_depth: 9
    n_jobs: -1

  requirements_units:
    learning_rate: 0.09
    colsample_bylevel: 0.8
    subsample: 0.8
    n_estimators: 150
    max_depth: 9
    n_jobs: -1

  requirements_weather:
    learning_rate: 0.09
    colsample_bylevel: 0.8
    subsample: 0.8
    n_estimators: 150
    max_depth: 9
    n_jobs: -1

  requirements_units_weather:
    learning_rate: 0.09
    colsample_bylevel: 0.8
    subsample: 0.8
    n_estimators: 150
    max_depth: 9
    n_jobs: -1

lstm_params:
  learning_rate: 0.001
  validation_size: 0.2
  sequence_length: 24
  batch_size : 32
  hidden_size: 128
  num_layers: 1
  output_dim: 1
  num_epochs: 20
  model: None